
INSERT INTO MEDIALX (MEDIAdm,MEDIALX) VALUES('01','television')
INSERT INTO MEDIALX (MEDIAdm,MEDIALX) VALUES('02','braodcast')
INSERT INTO MEDIALX (MEDIAdm,MEDIALX) VALUES('03','video')
INSERT INTO ADVERTISEMENT VALUES(1,'02','zhnag','2011-08-04','wei')